# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - project2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://project2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f222f769f7e84140abdbcc4d489498d6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a843d709f7a444bfa486452fbd17afc1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: project2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f222f769f7e84140abdbcc4d489498d6 }}/project2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'project2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_10ff29ba6dc24d8289d3382d48d20e48 }}
        images: 'project2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f222f769f7e84140abdbcc4d489498d6 }}/project2:${{ github.sha }}'